### ISSUE TITLE
Presumably wrong indentation in the code

### ISSUE THREAD

**Issue by Khumayun** [charan223/FairDeepLearning#8]
Wasting more than 3 hours I figured out that its on tab indentation left in mnist_loader.py [starting from here](https://github.com/charan223/FairDeepLearning/blob/ca883a3ee11bb5396dbf4552b2251cfb074094f0/dataloaders/mnist_loader.py#L320) down to next `if`.

**Comment by charan223** [comment]
Sorry for the delay, merged :)
